monitor=, 1920x1080@144, 0x0, 1.25

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar 
$menu = rofi -show drun
$lock = hyprlock

exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = blueman-applet

input {
    kb_layout = es,us
    kb_options = grp:win_space_toggle
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

xwayland {
    force_zero_scaling = true
}

decoration {
   rounding = 10
}

# SUPER + [1-9] desktop change
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# WINDOWS MOVE TO DESKTOP
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Super + Shift + S = Capturar toda la pantalla en la carpeta Imágenes
bind = $mainMod SHIFT, S, exec, grim ~/Images/$(date +'%Y-%m-%d_%H-%M-%S').png
# Super + S = Seleccionar un área con el mouse y abrir el editor Swappy
bind = $mainMod, S, exec, grim -g "$(slurp)" - | swappy -f -

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, L, exec, $lock
bind = $mainMod, Q, killactive
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu

windowrule = opacity 0.90 0.80, match:class ^(thunar)$
